name: Refactor

on:
    push: ~
    schedule:
        -
            cron: "0 2 * * *" # Run at 2am every day
    workflow_dispatch: ~
    
jobs:
    coding-standard-fixes:
        runs-on: ubuntu-latest
        
        name: "Coding standard fixes"
        
        timeout-minutes: 5
        
        steps:
            -
                uses: actions/checkout@v3

            -
                name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: 8.0
                    ini-values: date.timezone=Europe/Warsaw, opcache.enable=1, opcache.enable_cli=0, opcache.memory_consumption=512, opcache.max_accelerated_files=65407, opcache.interned_strings_buffer=8, opcache.validate_timestamps=0, opcache.save_comments=1, opcache.fast_shutdown=0
                    extensions: intl, gd, opcache, mysql, pdo_mysql
                    tools: symfony, composer-require-checker
                    coverage: none

            -
                name: Restrict Symfony version
                if: matrix.symfony != ''
                run: |
                    composer global require --no-progress --no-scripts --no-plugins "symfony/flex:1.18.5"
                    composer config extra.symfony.require "${{ matrix.symfony }}"
            -
                name: Get Composer cache directory
                id: composer-cache
                run: echo "::set-output name=dir::$(composer config cache-files-dir)"

            -
                name: Cache Composer
                uses: actions/cache@v2
                with:
                    path: ${{ steps.composer-cache.outputs.dir }}
                    key: ${{ runner.os }}-php-${{ matrix.php }}-symfony-${{ matrix.symfony }}-composer-${{ hashFiles('**/composer.json') }}
                    restore-keys: |
                        ${{ runner.os }}-php-${{ matrix.php }}-symfony-${{ matrix.symfony }}-composer-
            -
                name: Install PHP dependencies
                run: composer update --no-interaction --no-scripts
                id: end-of-setup

            -
                name: Run ECS
                run: vendor/bin/ecs check --fix src/Sylius

            -
                name: Create Pull Request
                uses: peter-evans/create-pull-request@v4
                with:
                    commit-message: Fix Coding Standard
                    author: SyliusBot
                    branch: coding-standard-fixes # TODO versions matrix
                    base: 1.10
